services:
  - type: web
    name: pokesim
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
